### ISSUE TITLE
Leights Opfor: Afghan militia

### ISSUE THREAD

**Issue by TheMagnetar** [SavageCDN/DAC_A3#14]
The entry "LOP_AM_Soldier" for the Afghan militia in the file LOP_dac_config_units.sqf should be replaced by "LOP_AM_Infantry_Rifleman" (Rifleman AKM), "LOP_AM_Infantry_Rifleman_2" (Rifleman AKMS) and "LOP_AM_Infantry_Rifleman_2" (Rifleman w. Lee Enfield).

"LOP_AM_Soldier" seems to no longer exist.

**Comment by Przemro** [comment]
I don`t followe LOP anymore, so thx for info - did a fix, so now should be ok.

**Comment by Przemro** [comment]
AFAIK this can be closed.
