### ISSUE TITLE
(LOP_dac_config_units ) Not all factions follow the Crewman/Pilot/Group Leader as first 3 entries rule.

### ISSUE THREAD

**Issue by JonBons** [SavageCDN/DAC_A3#8]
Not all factions follow the Crewman/Pilot/Group Leader as first 3 entries rule.

The entire LOP_dac_config_units file breaks that rule.

**Comment by Przemro** [comment]
I fixed it, just need to be checked and merged.

**Comment by SavageCDN** [comment]
Sorry been busy at work and vacationing... merged.
